### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by Carina0** [DarrenZhang01/ExCon#1]
First, I trained the model. But it had an error  **AttributeError: 'Namespace' object has no attribute 'threshold'.**  ./ExCon/util.py (line 209).  How to deal with?
Second,  how to run in 'ImageNet' dataset? In './ExCon/main_supcon.py (line648), there is no name 'eval_ebpg_miou_bbox'.

Looking forward to your reply.  Thank you very much!
Best wishes!

**Comment by DarrenZhang01** [comment]
Hi, I have updated the code and added the guide for the Tiny ImageNet dataset in README. Feel free to run it again. Thanks.
